### ISSUE TITLE
Quickstart: Hello, World on your local machine Should Not Throw Unhandled exception

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-dotnet#79]
I was following this quickstart:

https://github.com/GoogleCloudPlatform/functions-framework-dotnet#quickstart-hello-world-on-your-local-machine

Setup:

```sh
mkdir HelloFunctions
cd HelloFunctions
dotnet new gcf-http
The template "Google Cloud Functions HttpFunction" was created successfully.
```

Run:

```sh
 dotnet run
Unhandled exception. System.Exception: Can't load specified function type 'helloHttp'
   at Google.Cloud.Functions.Invoker.FunctionEnvironment.Builder.DetermineFunctionType()
   at Google.Cloud.Functions.Invoker.FunctionEnvironment.Builder.Build()
   at Google.Cloud.Functions.Invoker.FunctionEnvironment.Create(Assembly functionAssembly, String[] commandLine, ConfigurationVariableProvider variableProvider)
   at Google.Cloud.Functions.Invoker.EntryPoint.StartAsync(Assembly functionAssembly, String[] args)
   at AutoGeneratedProgram.<Main>(String[] args)
```

Got an exception.

Missing a `FUNCTION_TARGET` instruction? Maybe a different error message would help.

**Comment by jskeet** [comment]
I suspect you had the `FUNCTION_TARGET` environment variable set to `helloHttp`, in which case this is behaving as expceted.

(I can't see where else the name `helloHttp` would come from.)

**Comment by grant** [comment]
Yeah, makes sense.
Resetting `FUNCTION_TARGET=''` fixes things.
Should not happen to most users. Thanks for helping!
